//! Comprehensive test suite for Fusion's `/goal` and `/plan` slash command handlers (`src/ui/slash_plan.rs`).

use fusion::agent;

#[path = "../src/ui/slash_plan.rs"]
pub mod slash_plan;

use fusion::agent::planner_dag::{DagTask, DagTaskPriority, SubagentDag};
use fusion::agent::subagent::SubagentRole;
use slash_plan::{
    execute_active_plan, format_execution_report, handle_goal_command, handle_plan_command,
    StandardFeature,
};

// =========================================================================
// 1. Tests for `handle_goal_command`
// =========================================================================

#[test]
fn test_handle_goal_command_basic() {
    let prompt = "Implement user authentication with JWT and refresh tokens";
    let (preview, dag) = handle_goal_command(prompt);

    // Verify DAG metadata
    assert_eq!(dag.goal, prompt);
    assert!(dag.name.starts_with("Plan: "));
    assert!(dag.name.contains("Implement user authentication"));
    assert!(!dag.id.is_empty());

    // Verify tasks generated by standard feature strategy
    assert!(dag.task_count() >= 4);
    assert!(dag.tasks.contains_key("scout_arch"));
    assert!(dag.tasks.contains_key("coder_core") || dag.tasks.contains_key("coder_feature"));
    assert!(dag.tasks.contains_key("tester_integration"));

    // Verify stages were computed
    assert!(!dag.stages.is_empty());

    // Verify preview output
    assert!(preview.contains("DAG Plan:"));
    assert!(preview.contains(&dag.name));
    assert!(preview.contains(&dag.id));
    assert!(preview.contains(prompt));
    assert!(preview.contains("Overall Status:"));
    assert!(preview.contains("scout_arch"));
}

#[test]
fn test_handle_goal_command_empty_prompt() {
    let (preview, dag) = handle_goal_command("");

    // Verify non-panicking, returns valid DAG
    assert!(!dag.id.is_empty());
    assert!(!preview.is_empty());
    assert!(preview.contains("DAG Plan:"));
}

#[test]
fn test_handle_goal_command_whitespace_prompt() {
    let (preview, dag) = handle_goal_command("   \n\t  ");

    assert!(!dag.id.is_empty());
    assert!(!preview.is_empty());
    assert!(preview.contains("DAG Plan:"));
}

#[test]
fn test_handle_goal_command_multiline_prompt() {
    let multiline = "Add SQLite session storage engine\n- Support ACID transactions\n- Auto migrate old sessions\n- Add benchmark tests";
    let (preview, dag) = handle_goal_command(multiline);

    assert_eq!(dag.goal, multiline);
    assert_eq!(dag.name, "Plan: Add SQLite session storage engine");
    assert!(preview.contains("Plan: Add SQLite session storage engine"));
    assert!(preview.contains("Add SQLite session storage engine"));
}

#[test]
fn test_handle_goal_command_roles_and_dependencies() {
    let (preview, dag) = handle_goal_command("Refactor config parser to use TOML and YAML");

    // Scout role check
    let scout = dag.get_task("scout_arch").expect("scout_arch task");
    assert_eq!(scout.role, SubagentRole::Scout);
    assert!(scout.dependencies.is_empty());

    // Core coder check
    if let Some(coder) = dag.get_task("coder_core") {
        assert_eq!(coder.role, SubagentRole::Coder);
        assert!(coder.dependencies.contains(&"scout_arch".to_string()));
    }

    // Tester check
    if let Some(tester) = dag.get_task("tester_integration") {
        assert_eq!(tester.role, SubagentRole::Tester);
    }

    // Preview contains roles
    assert!(preview.contains("Scout"));
}

// =========================================================================
// 2. Tests for `handle_plan_command` without an active DAG
// =========================================================================

#[test]
fn test_handle_plan_command_status_no_active_dag() {
    let output = handle_plan_command(&["status".to_string()], None);
    assert!(output.contains("No active plan"));
    assert!(output.contains("/goal"));
}

#[test]
fn test_handle_plan_command_stages_no_active_dag() {
    let output = handle_plan_command(&["stages".to_string()], None);
    assert!(output.contains("No active plan"));
    assert!(output.contains("/goal"));
}

#[test]
fn test_handle_plan_command_cancel_no_active_dag() {
    let output = handle_plan_command(&["cancel".to_string()], None);
    assert!(output.contains("No active plan to cancel"));
}

#[test]
fn test_handle_plan_command_run_no_active_dag() {
    for cmd in &["run", "execute", "start"] {
        let output = handle_plan_command(&[cmd.to_string()], None);
        assert_eq!(
            output,
            "No active plan to run. Use /goal <objective> first to create a plan."
        );
    }
}

// =========================================================================
// 3. Tests for `handle_plan_command` with an active DAG
// =========================================================================

#[test]
fn test_handle_plan_command_status_active() {
    let (_, dag) = handle_goal_command("Implement rate limiter middleware");
    let output = handle_plan_command(&["status".to_string()], Some(&dag));

    assert!(output.contains("DAG Plan:"));
    assert!(output.contains(&dag.name));
    assert!(output.contains(&dag.id));
    assert!(output.contains("Implement rate limiter middleware"));
    assert!(output.contains("Overall Status:"));
    assert_eq!(output, dag.to_ascii_tree());
}

#[test]
fn test_handle_plan_command_stages_active() {
    let (_, dag) = handle_goal_command("Implement rate limiter middleware");
    let output = handle_plan_command(&["stages".to_string()], Some(&dag));

    // Verify plan header
    assert!(output.contains("Stages for Plan:"));
    assert!(output.contains(&dag.name));
    assert!(output.contains(&dag.id));
    assert!(output.contains("Implement rate limiter middleware"));

    // Verify constituent stages
    assert!(output.contains("▶"));
    assert!(output.contains("Stage 1"));

    // Verify constituent tasks, descriptions, roles, statuses
    assert!(output.contains("scout_arch"));
    assert!(output.contains("Role: Scout"));
    assert!(output.contains("Status: Pending"));
    assert!(output.contains("Description:"));
    assert!(output.contains("Analyze codebase architecture"));
}

#[test]
fn test_handle_plan_command_cancel_active() {
    let (_, dag) = handle_goal_command("Implement rate limiter middleware");
    let output = handle_plan_command(&["cancel".to_string()], Some(&dag));

    assert!(output.contains("cancelled and reset"));
}

#[test]
fn test_handle_plan_command_run_active() {
    let (_, dag) = handle_goal_command("Implement rate limiter middleware");
    for cmd in &["run", "execute", "start"] {
        let output = handle_plan_command(&[cmd.to_string()], Some(&dag));
        assert!(output.contains("Plan Execution Report:"));
        assert!(output.contains(&dag.name));
        assert!(output.contains("Status:"));
        assert!(output.contains("Stages Executed:"));
        assert!(output.contains("Subagent Tasks Run:"));
        assert!(output.contains("Tokens Spent:"));
    }
}

#[test]
fn test_handle_plan_command_run_completed_dag() {
    let (_, mut dag) = handle_goal_command("Implement rate limiter middleware");
    // Compute stages and complete all tasks
    dag.compute_stages().unwrap();
    let task_ids: Vec<String> = dag.tasks.keys().cloned().collect();
    for id in task_ids {
        dag.mark_task_completed(&id, "Output for task".to_string(), 100);
    }
    let num_stages = dag.stages.len();

    let output = handle_plan_command(&["run".to_string()], Some(&dag));
    assert!(output.contains(&format!("[✓] Completed in {} stages", num_stages)));
    assert!(output.contains(&format!(
        "Stages Executed:     {}/{} completed",
        num_stages, num_stages
    )));
}

// =========================================================================
// 4. Tests for command options, case-insensitivity, and help
// =========================================================================

#[test]
fn test_handle_plan_command_empty_args() {
    let (_, dag) = handle_goal_command("Build caching layer");
    let output = handle_plan_command(&[], Some(&dag));

    assert!(output.contains("Usage: /plan"));
    assert!(output.contains("status"));
    assert!(output.contains("stages"));
    assert!(output.contains("cancel"));
}

#[test]
fn test_handle_plan_command_help_flag() {
    let (_, dag) = handle_goal_command("Build caching layer");

    for help_arg in &["help", "-h", "--help"] {
        let output = handle_plan_command(&[help_arg.to_string()], Some(&dag));
        assert!(output.contains("Usage: /plan"));
        assert!(output.contains("status"));
        assert!(output.contains("stages"));
        assert!(output.contains("cancel"));
    }
}

#[test]
fn test_handle_plan_command_unknown_subcommand() {
    let (_, dag) = handle_goal_command("Build caching layer");
    let output = handle_plan_command(&["unknown_cmd".to_string()], Some(&dag));

    assert!(output.contains("Unknown plan subcommand: 'unknown_cmd'"));
    assert!(output.contains("status, stages, cancel"));
}

#[test]
fn test_handle_plan_command_case_insensitivity() {
    let (_, dag) = handle_goal_command("Build caching layer");

    let status_lower = handle_plan_command(&["status".to_string()], Some(&dag));
    let status_upper = handle_plan_command(&["STATUS".to_string()], Some(&dag));
    let status_mixed = handle_plan_command(&["StAtUs".to_string()], Some(&dag));
    assert_eq!(status_lower, status_upper);
    assert_eq!(status_lower, status_mixed);

    let cancel_lower = handle_plan_command(&["cancel".to_string()], Some(&dag));
    let cancel_upper = handle_plan_command(&["CANCEL".to_string()], Some(&dag));
    assert_eq!(cancel_lower, cancel_upper);
}

#[test]
fn test_handle_plan_command_whitespace_tolerance() {
    let (_, dag) = handle_goal_command("Build caching layer");

    let status_clean = handle_plan_command(&["status".to_string()], Some(&dag));
    let status_padded = handle_plan_command(&["   status   ".to_string()], Some(&dag));
    assert_eq!(status_clean, status_padded);

    let stages_clean = handle_plan_command(&["stages".to_string()], Some(&dag));
    let stages_padded = handle_plan_command(&["\tstages\n".to_string()], Some(&dag));
    assert_eq!(stages_clean, stages_padded);
}

// =========================================================================
// 5. Tests for edge-case DAGs and lifecycle updates
// =========================================================================

#[test]
fn test_handle_plan_command_stages_empty_dag() {
    let empty_dag = SubagentDag::new("Empty Plan", "Do nothing");
    let output = handle_plan_command(&["stages".to_string()], Some(&empty_dag));

    assert!(output.contains("Stages for Plan: Empty Plan"));
    assert!(output.contains("No stages or tasks defined in active plan."));
}

#[test]
fn test_handle_plan_command_stages_unpartitioned_dag() {
    let mut unpartitioned_dag = SubagentDag::new("Manual Plan", "Custom manual tasks");
    let t1 = DagTask::new(
        "task_1",
        "Initial Probe",
        SubagentRole::Scout,
        "Examine environment and tools",
    )
    .with_priority(DagTaskPriority::High);
    let t2 = DagTask::new(
        "task_2",
        "Secondary Step",
        SubagentRole::Coder,
        "Write custom adapter code",
    )
    .with_dependency("task_1");

    unpartitioned_dag.add_task(t1).unwrap();
    unpartitioned_dag.add_task(t2).unwrap();

    let output = handle_plan_command(&["stages".to_string()], Some(&unpartitioned_dag));
    assert!(output.contains("Tasks (Unpartitioned):"));
    assert!(output.contains("task_1"));
    assert!(output.contains("Initial Probe"));
    assert!(output.contains("Examine environment and tools"));
    assert!(output.contains("task_2"));
    assert!(output.contains("Write custom adapter code"));
    assert!(output.contains("Dependencies: task_1"));
}

#[test]
fn test_handle_plan_command_status_lifecycle_updates() {
    let (_, mut dag) = handle_goal_command("Implement WebSocket streaming");

    // Initially Not Started
    let initial_status = handle_plan_command(&["status".to_string()], Some(&dag));
    assert!(initial_status.contains("Overall Status: Not Started"));

    // Complete scout task
    dag.mark_task_completed("scout_arch", "Exploration complete".to_string(), 150);

    let updated_status = handle_plan_command(&["status".to_string()], Some(&dag));
    assert!(updated_status.contains("[✓] [Scout] scout_arch"));
    assert!(updated_status.contains("(150ms)"));
    assert!(updated_status.contains("Overall Status: In Progress"));
}

#[test]
fn test_standard_feature_constant() {
    use fusion::agent::planner_dag::DecompositionStrategy;
    assert_eq!(
        StandardFeature,
        DecompositionStrategy::SoftwareFeature {
            split_frontend_backend: true,
            include_security_audit: true,
        }
    );
}

// =========================================================================
// 6. Tests for `execute_active_plan` and `format_execution_report`
// =========================================================================

#[test]
fn test_format_execution_report_structure() {
    let (_, dag) = handle_goal_command("Implement rate limiter middleware");
    let summary = fusion::agent::plan_runner::PlanSummary::from_dag(&dag);
    let report = format_execution_report(&summary);

    assert!(report.contains("Plan Execution Report:"));
    assert!(report.contains(&dag.name));
    assert!(report.contains("Goal:"));
    assert!(report.contains("Status:"));
    assert!(report.contains("Stages Executed:"));
    assert!(report.contains("Subagent Tasks Run:"));
    assert!(report.contains("Tokens Spent:"));
}

#[tokio::test]
async fn test_execute_active_plan_empty_dag() {
    let mut dag = SubagentDag::new("Empty Plan", "Do nothing");
    let client = std::sync::Arc::new(fusion::provider::LlmClient::new());
    let manager = fusion::agent::subagent::SubagentManager::new(
        client,
        fusion::config::Config::default(),
        fusion::tools::ToolRegistry::new(),
    );

    let result = execute_active_plan(&mut dag, &manager).await;
    assert!(result.is_err());
    let err = result.unwrap_err();
    assert_eq!(err, fusion::agent::plan_runner::PlanRunnerError::EmptyPlan);
}
