use chrono::Utc;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use uuid::Uuid;

use crate::config::Config;
use crate::provider::types::{Message, ToolCall};

/// Detailed token usage statistics for a session.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct TokenStats {
    /// Tokens in prompts sent to the model.
    #[serde(default)]
    pub prompt_tokens: u64,
    /// Tokens generated by the model in completions.
    #[serde(default)]
    pub completion_tokens: u64,
    /// Total tokens consumed (prompt + completion).
    #[serde(default)]
    pub total_tokens: u64,
    /// Cached tokens read from provider context cache (if supported).
    #[serde(default)]
    pub cache_read_tokens: u64,
    /// Cached tokens written to provider context cache (if supported).
    #[serde(default)]
    pub cache_write_tokens: u64,
    /// Number of completed turns/requests in this session.
    #[serde(default)]
    pub total_turns: u64,
}

/// Type alias for TokenStats for backwards and ergonomic compatibility.
pub type TokenUsage = TokenStats;

impl TokenStats {
    /// Creates a new, zeroed `TokenStats` structure.
    pub const fn new() -> Self {
        Self {
            prompt_tokens: 0,
            completion_tokens: 0,
            total_tokens: 0,
            cache_read_tokens: 0,
            cache_write_tokens: 0,
            total_turns: 0,
        }
    }

    /// Adds prompt and completion tokens to the running totals and increments turn counter.
    pub fn add(&mut self, prompt: u64, completion: u64) {
        self.prompt_tokens = self.prompt_tokens.saturating_add(prompt);
        self.completion_tokens = self.completion_tokens.saturating_add(completion);
        self.total_tokens = self
            .total_tokens
            .saturating_add(prompt)
            .saturating_add(completion);
        self.total_turns = self.total_turns.saturating_add(1);
    }

    /// Records tokens from optional `u32` values (e.g. from LLM stream termination chunks).
    pub fn record_turn(&mut self, prompt: Option<u32>, completion: Option<u32>) {
        let p = prompt.unwrap_or(0) as u64;
        let c = completion.unwrap_or(0) as u64;
        self.add(p, c);
    }

    /// Records cache tokens read and written.
    pub fn record_cache(&mut self, read: u64, write: u64) {
        self.cache_read_tokens = self.cache_read_tokens.saturating_add(read);
        self.cache_write_tokens = self.cache_write_tokens.saturating_add(write);
    }

    /// Resets all statistics counters back to zero.
    pub fn reset(&mut self) {
        *self = Self::new();
    }

    /// Formats a concise, human-readable summary of token usage.
    pub fn format_summary(&self) -> String {
        format!(
            "Tokens: {} total ({} prompt, {} completion) across {} turn{}",
            self.total_tokens,
            self.prompt_tokens,
            self.completion_tokens,
            self.total_turns,
            if self.total_turns == 1 { "" } else { "s" }
        )
    }
}

/// Represents a persistent conversational session.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Session {
    /// Unique session identifier (UUID v4).
    pub id: Uuid,
    /// ISO 8601 / RFC 3339 timestamp when the session was created.
    pub created_at: String,
    /// ISO 8601 / RFC 3339 timestamp when the session was last updated.
    pub updated_at: String,
    /// The active LLM model identifier for this session.
    pub active_model: String,
    /// Optional user-defined or auto-generated session title.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Chronological list of conversation messages.
    pub messages: Vec<Message>,
    /// Accumulated token usage statistics for this session.
    #[serde(default, alias = "token_usage")]
    pub token_stats: TokenStats,
    /// Optional system prompt attached to this session.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub system_prompt: Option<String>,
    /// Optional working directory where this session was initiated.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub working_dir: Option<PathBuf>,
    /// Arbitrary session-level metadata key-value pairs.
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub metadata: HashMap<String, String>,
    /// Explicit structured execution state Σ for SKILL.state bounded prompt runtime (arXiv:2608.26263).
    #[serde(
        default,
        skip_serializing_if = "crate::agent::skill_state::SkillState::is_empty"
    )]
    pub execution_state: crate::agent::skill_state::SkillState,
}

/// Lightweight summary of a session for listing / UI selection.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionSummary {
    pub id: Uuid,
    pub created_at: String,
    pub updated_at: String,
    pub active_model: String,
    pub title: Option<String>,
    pub message_count: usize,
    pub preview: String,
}

impl Session {
    /// Creates a new Session with a freshly generated UUID v4 and the current timestamp.
    pub fn new(model: impl Into<String>) -> Self {
        let now = Utc::now().to_rfc3339();
        Self {
            id: Uuid::new_v4(),
            created_at: now.clone(),
            updated_at: now,
            active_model: model.into(),
            title: None,
            messages: Vec::new(),
            token_stats: TokenStats::new(),
            system_prompt: None,
            working_dir: None,
            metadata: HashMap::new(),
            execution_state: crate::agent::skill_state::SkillState::new(),
        }
    }

    /// Creates a session with a specified UUID.
    pub fn with_id(id: Uuid, model: impl Into<String>) -> Self {
        let now = Utc::now().to_rfc3339();
        Self {
            id,
            created_at: now.clone(),
            updated_at: now,
            active_model: model.into(),
            title: None,
            messages: Vec::new(),
            token_stats: TokenStats::new(),
            system_prompt: None,
            working_dir: None,
            metadata: HashMap::new(),
            execution_state: crate::agent::skill_state::SkillState::new(),
        }
    }

    /// Creates a session with an explicit system prompt.
    pub fn with_system_prompt(model: impl Into<String>, system_prompt: impl Into<String>) -> Self {
        let mut session = Self::new(model);
        session.system_prompt = Some(system_prompt.into());
        session
    }

    /// Returns the session ID.
    pub fn id(&self) -> Uuid {
        self.id
    }

    /// Returns the session ID formatted as a standard string.
    pub fn id_str(&self) -> String {
        self.id.to_string()
    }

    /// Returns the creation timestamp in RFC 3339 format.
    pub fn created_at(&self) -> &str {
        &self.created_at
    }

    /// Returns the last update timestamp in RFC 3339 format.
    pub fn updated_at(&self) -> &str {
        &self.updated_at
    }

    /// Returns the active model for this session.
    pub fn active_model(&self) -> &str {
        &self.active_model
    }

    /// Sets the active model.
    pub fn set_active_model(&mut self, model: impl Into<String>) {
        self.active_model = model.into();
        self.touch();
    }

    /// Returns the optional session title.
    pub fn title(&self) -> Option<&str> {
        self.title.as_deref()
    }

    /// Sets an optional title or summary for the session.
    pub fn set_title(&mut self, title: impl Into<String>) {
        self.title = Some(title.into());
        self.touch();
    }

    /// Returns an immutable reference to the messages in this session.
    pub fn messages(&self) -> &[Message] {
        &self.messages
    }

    /// Returns a mutable reference to the messages in this session.
    pub fn messages_mut(&mut self) -> &mut Vec<Message> {
        self.touch();
        &mut self.messages
    }

    /// Returns the total number of messages in the session.
    pub fn total_messages(&self) -> usize {
        self.messages.len()
    }

    /// Returns an immutable reference to token usage statistics.
    pub fn token_stats(&self) -> &TokenStats {
        &self.token_stats
    }

    /// Returns a mutable reference to token usage statistics.
    pub fn token_stats_mut(&mut self) -> &mut TokenStats {
        self.touch();
        &mut self.token_stats
    }

    /// Records token usage from an LLM turn.
    pub fn record_tokens(&mut self, prompt: Option<u32>, completion: Option<u32>) {
        self.token_stats.record_turn(prompt, completion);
        self.touch();
    }

    /// Records explicit u64 token counts.
    pub fn record_usage(&mut self, prompt: u64, completion: u64) {
        self.token_stats.add(prompt, completion);
        self.touch();
    }

    /// Estimates the monetary cost (USD) of the tokens consumed in this session so far.
    pub fn estimate_cost(
        &self,
        default_provider: Option<&str>,
    ) -> crate::agent::cost::CostBreakdown {
        crate::agent::cost::estimate_session_cost(self, default_provider)
    }

    /// Returns the optional system prompt.
    pub fn system_prompt(&self) -> Option<&str> {
        self.system_prompt.as_deref()
    }

    /// Sets the session system prompt.
    pub fn set_system_prompt(&mut self, prompt: impl Into<String>) {
        self.system_prompt = Some(prompt.into());
        self.touch();
    }

    /// Returns the optional working directory.
    pub fn working_dir(&self) -> Option<&Path> {
        self.working_dir.as_deref()
    }

    /// Sets the working directory.
    pub fn set_working_dir(&mut self, dir: impl Into<PathBuf>) {
        self.working_dir = Some(dir.into());
        self.touch();
    }

    /// Returns session metadata.
    pub fn metadata(&self) -> &HashMap<String, String> {
        &self.metadata
    }

    /// Sets a metadata key-value pair.
    pub fn set_metadata(&mut self, key: impl Into<String>, value: impl Into<String>) {
        self.metadata.insert(key.into(), value.into());
        self.touch();
    }

    /// Retrieves a metadata value by key.
    pub fn get_metadata(&self, key: &str) -> Option<&str> {
        self.metadata.get(key).map(|s| s.as_str())
    }

    /// Updates the updated_at timestamp to current UTC time.
    pub fn touch(&mut self) {
        self.updated_at = Utc::now().to_rfc3339();
    }

    /// Adds a general message and updates the timestamp.
    /// If no title is present, auto-derives one from the first user message.
    pub fn add_message(&mut self, message: Message) {
        if self.title.is_none() && message.role == crate::provider::types::Role::User {
            let trimmed = message.content.trim();
            if !trimmed.is_empty() {
                let title: String = trimmed.chars().take(60).collect();
                self.title = Some(title);
            }
        }
        self.messages.push(message);
        self.touch();
    }

    /// Adds a system message.
    pub fn add_system_message(&mut self, content: impl Into<String>) {
        self.add_message(Message::system(content));
    }

    /// Adds a user message.
    pub fn add_user_message(&mut self, content: impl Into<String>) {
        self.add_message(Message::user(content));
    }

    /// Adds an assistant response message.
    pub fn add_assistant_message(&mut self, content: impl Into<String>) {
        self.add_message(Message::assistant(content));
    }

    /// Adds an assistant message containing tool calls.
    pub fn add_assistant_with_tools(
        &mut self,
        content: impl Into<String>,
        tool_calls: Vec<ToolCall>,
    ) {
        self.add_message(Message::assistant_with_tools(content, tool_calls));
    }

    /// Adds a tool execution result.
    pub fn add_tool_result(&mut self, tool_call_id: impl Into<String>, content: impl Into<String>) {
        self.add_message(Message::tool_result(tool_call_id, content));
    }

    /// Returns the last message in the conversation, if any.
    pub fn last_message(&self) -> Option<&Message> {
        self.messages.last()
    }

    /// Clears all messages from the session (synonym for `clear()`).
    pub fn clear_messages(&mut self) {
        self.messages.clear();
        self.touch();
    }

    /// Clears all messages from the session.
    pub fn clear(&mut self) {
        self.clear_messages();
    }

    /// Truncates messages to the specified maximum length.
    pub fn truncate(&mut self, len: usize) {
        if self.messages.len() > len {
            self.messages.truncate(len);
            self.touch();
        }
    }

    /// Estimates the current token count across all messages in this session.
    pub fn estimate_tokens(&self) -> usize {
        crate::agent::compaction::estimate_messages_tokens(&self.messages)
    }

    /// Returns `true` if the session's messages exceed the context budget
    /// (by default 80% of the active model's context window limit).
    pub fn needs_compaction(
        &self,
        compactor: Option<&crate::agent::compaction::Compactor>,
    ) -> bool {
        if let Some(c) = compactor {
            c.needs_compaction(&self.messages, &self.active_model)
        } else {
            let default_c = crate::agent::compaction::Compactor::default();
            default_c.needs_compaction(&self.messages, &self.active_model)
        }
    }

    /// Intelligently compacts the conversation history in-place using the specified
    /// or default Compactor.
    pub fn compact(
        &mut self,
        compactor: &crate::agent::compaction::Compactor,
    ) -> crate::agent::compaction::CompactionResult {
        let res = compactor.compact_session(self);
        if res.compacted {
            self.touch();
        }
        res
    }

    // --- Persistence & Resumption ---

    /// Returns the directory where sessions are stored: `~/.fusion/sessions`
    pub fn sessions_dir() -> PathBuf {
        Config::config_dir().join("sessions")
    }

    /// Returns the standard file path for a session by UUID: `~/.fusion/sessions/<id>.json`
    pub fn session_path(id: Uuid) -> PathBuf {
        Self::sessions_dir().join(format!("{}.json", id))
    }

    /// Saves the session to `~/.fusion/sessions/<id>.json`.
    pub fn save(&self) -> anyhow::Result<PathBuf> {
        let dir = Self::sessions_dir();
        if !dir.exists() {
            fs::create_dir_all(&dir)?;
        }
        let path = Self::session_path(self.id);
        self.save_to_path(&path)?;
        Ok(path)
    }

    /// Saves the session to an explicit file path.
    pub fn save_to_path(&self, path: impl AsRef<Path>) -> anyhow::Result<PathBuf> {
        let path = path.as_ref();
        if let Some(parent) = path.parent() {
            if !parent.exists() {
                fs::create_dir_all(parent)?;
            }
        }
        let json = serde_json::to_string_pretty(self)?;
        fs::write(path, json)?;
        Ok(path.to_path_buf())
    }

    /// Loads a session from `~/.fusion/sessions/<id>.json`.
    pub fn load(id: Uuid) -> anyhow::Result<Self> {
        let path = Self::session_path(id);
        if !path.exists() {
            anyhow::bail!("Session not found: {}", id);
        }
        Self::load_from_path(&path)
    }

    /// Loads a session by UUID string or prefix.
    pub fn load_from_str(id_or_prefix: &str) -> anyhow::Result<Self> {
        let trimmed = id_or_prefix.trim();
        if let Ok(uuid) = Uuid::parse_str(trimmed) {
            return Self::load(uuid);
        }

        // Try prefix match in sessions directory
        if let Some(session) = Self::find_by_prefix(trimmed)? {
            return Ok(session);
        }

        anyhow::bail!("No session found matching ID or prefix: '{}'", id_or_prefix);
    }

    /// Loads a session from an arbitrary JSON file path.
    pub fn load_from_path(path: impl AsRef<Path>) -> anyhow::Result<Self> {
        let content = fs::read_to_string(path)?;
        let session: Session = serde_json::from_str(&content)?;
        Ok(session)
    }

    /// Resumes an existing session by loading it and updating its timestamp.
    pub fn resume(id: Uuid) -> anyhow::Result<Self> {
        let mut session = Self::load(id)?;
        session.touch();
        Ok(session)
    }

    /// Resumes the most recently modified session from disk.
    pub fn resume_latest() -> anyhow::Result<Option<Self>> {
        let summaries = Self::list_sessions()?;
        if let Some(first) = summaries.first() {
            let session = Self::resume(first.id)?;
            Ok(Some(session))
        } else {
            Ok(None)
        }
    }

    /// Searches for a session whose UUID begins with the given prefix.
    pub fn find_by_prefix(prefix: &str) -> anyhow::Result<Option<Self>> {
        let dir = Self::sessions_dir();
        if !dir.exists() {
            return Ok(None);
        }

        let prefix_clean = prefix.trim().to_lowercase();
        let mut matching_paths = Vec::new();

        for entry in fs::read_dir(dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) == Some("json") {
                if let Some(file_stem) = path.file_stem().and_then(|s| s.to_str()) {
                    if file_stem.to_lowercase().starts_with(&prefix_clean) {
                        matching_paths.push(path);
                    }
                }
            }
        }

        if matching_paths.is_empty() {
            Ok(None)
        } else if matching_paths.len() == 1 {
            let session = Self::load_from_path(&matching_paths[0])?;
            Ok(Some(session))
        } else {
            anyhow::bail!(
                "Ambiguous session prefix '{}' matches {} sessions",
                prefix,
                matching_paths.len()
            );
        }
    }

    /// Deletes a saved session from disk.
    pub fn delete(id: Uuid) -> anyhow::Result<()> {
        let path = Self::session_path(id);
        Self::delete_by_path(path)
    }

    /// Deletes a session file at the specified path.
    pub fn delete_by_path(path: impl AsRef<Path>) -> anyhow::Result<()> {
        let path = path.as_ref();
        if path.exists() {
            fs::remove_file(path)?;
        }
        Ok(())
    }

    /// Lists all saved sessions, sorted by most recently updated first.
    pub fn list_sessions() -> anyhow::Result<Vec<SessionSummary>> {
        let dir = Self::sessions_dir();
        if !dir.exists() {
            return Ok(Vec::new());
        }

        let mut summaries = Vec::new();
        for entry in fs::read_dir(dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) == Some("json") {
                if let Ok(session) = Self::load_from_path(&path) {
                    let preview = session
                        .messages
                        .iter()
                        .rev()
                        .find(|m| {
                            m.role == crate::provider::types::Role::User
                                || m.role == crate::provider::types::Role::Assistant
                        })
                        .map(|m| {
                            let mut p: String = m.content.chars().take(80).collect();
                            if m.content.chars().count() > 80 {
                                p.push_str("...");
                            }
                            p
                        })
                        .unwrap_or_else(|| "Empty session".to_string());

                    summaries.push(SessionSummary {
                        id: session.id,
                        created_at: session.created_at,
                        updated_at: session.updated_at,
                        active_model: session.active_model,
                        title: session.title,
                        message_count: session.messages.len(),
                        preview,
                    });
                }
            }
        }

        // Sort descending by updated_at (most recent first)
        summaries.sort_by(|a, b| b.updated_at.cmp(&a.updated_at));
        Ok(summaries)
    }

    /// Searches all saved sessions in `~/.fusion/sessions/` using full-text BM25 or semantic matching.
    pub fn search_all(query_str: &str) -> anyhow::Result<crate::agent::search::SearchReport> {
        crate::agent::search::search_sessions(query_str)
    }

    /// Searches saved sessions in a specified directory using structured query options.
    pub fn search_dir(
        dir: impl AsRef<Path>,
        query: &crate::agent::search::SearchQuery,
    ) -> anyhow::Result<crate::agent::search::SearchReport> {
        crate::agent::search::search_sessions_dir(dir, query)
    }

    /// Exports the full session conversation to formatted Markdown.
    pub fn export_markdown(&self) -> String {
        let mut md = String::new();
        let title = self.title.as_deref().unwrap_or("Fusion Session");
        md.push_str(&format!("# {}\n\n", title));
        md.push_str(&format!("- **Session ID:** `{}`\n", self.id));
        md.push_str(&format!("- **Model:** `{}`\n", self.active_model));
        md.push_str(&format!("- **Created:** {}\n", self.created_at));
        md.push_str(&format!("- **Updated:** {}\n", self.updated_at));
        md.push_str(&format!(
            "- **Tokens:** {}\n\n",
            self.token_stats.format_summary()
        ));
        md.push_str("---\n\n");

        for msg in &self.messages {
            match msg.role {
                crate::provider::types::Role::System => {
                    md.push_str("### ⚙️ System\n\n");
                    md.push_str(&msg.content);
                    md.push_str("\n\n");
                }
                crate::provider::types::Role::User => {
                    md.push_str("### 👤 User\n\n");
                    md.push_str(&msg.content);
                    md.push_str("\n\n");
                }
                crate::provider::types::Role::Assistant => {
                    md.push_str("### 🤖 Assistant\n\n");
                    md.push_str(&msg.content);
                    md.push_str("\n\n");
                    if let Some(calls) = &msg.tool_calls {
                        for call in calls {
                            md.push_str(&format!(
                                "> 🛠️ **Tool Call:** `{}` (`{}`)\n",
                                call.name, call.id
                            ));
                            md.push_str("```json\n");
                            md.push_str(&call.arguments);
                            md.push_str("\n```\n\n");
                        }
                    }
                }
                crate::provider::types::Role::Tool => {
                    let call_id = msg.tool_call_id.as_deref().unwrap_or("unknown");
                    md.push_str(&format!("### 🔧 Tool Output (`{}`)\n\n", call_id));
                    md.push_str("```\n");
                    md.push_str(&msg.content);
                    md.push_str("\n```\n\n");
                }
            }
        }

        md
    }

    /// Exports the full session conversation to a self-contained, syntax-highlighted HTML document.
    pub fn export_html(&self) -> String {
        crate::agent::export::export_session_html(self)
    }

    /// Exports the full session conversation to a self-contained HTML file on disk.
    pub fn export_html_file(&self, path: impl AsRef<std::path::Path>) -> std::io::Result<()> {
        crate::agent::export::export_session_html_file(self, path)
    }

    /// Generates a unified diff string representing all file modifications in this session.
    pub fn export_patch(&self) -> String {
        crate::agent::session_patch::export_session_patch_string(
            self,
            &crate::agent::session_patch::SessionPatchOptions::default(),
        )
    }

    /// Generates a unified diff string representing all file modifications with customized options.
    pub fn export_patch_with_options(
        &self,
        options: &crate::agent::session_patch::SessionPatchOptions,
    ) -> String {
        crate::agent::session_patch::export_session_patch_string(self, options)
    }

    /// Saves all session file edits into a single `session.patch` file at the specified path.
    pub fn export_patch_file(
        &self,
        path: impl AsRef<std::path::Path>,
    ) -> std::io::Result<std::path::PathBuf> {
        crate::agent::session_patch::export_session_patch_file(
            self,
            path,
            &crate::agent::session_patch::SessionPatchOptions::default(),
        )
    }

    /// Saves all session file edits into a patch file with customized options.
    pub fn export_patch_file_with_options(
        &self,
        path: impl AsRef<std::path::Path>,
        options: &crate::agent::session_patch::SessionPatchOptions,
    ) -> std::io::Result<std::path::PathBuf> {
        crate::agent::session_patch::export_session_patch_file(self, path, options)
    }

    /// Generates a structured `SessionPatch` object containing all file diffs and statistics.
    pub fn session_patch(&self) -> crate::agent::session_patch::SessionPatch {
        crate::agent::session_patch::export_session_patch(
            self,
            &crate::agent::session_patch::SessionPatchOptions::default(),
        )
    }

    /// Generates a structured `SessionPatch` object with customized options.
    pub fn session_patch_with_options(
        &self,
        options: &crate::agent::session_patch::SessionPatchOptions,
    ) -> crate::agent::session_patch::SessionPatch {
        crate::agent::session_patch::export_session_patch(self, options)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::provider::types::Role;

    #[test]
    fn test_token_stats_tracking() {
        let mut stats = TokenStats::new();
        assert_eq!(stats.total_tokens, 0);
        assert_eq!(stats.total_turns, 0);

        stats.add(100, 50);
        assert_eq!(stats.prompt_tokens, 100);
        assert_eq!(stats.completion_tokens, 50);
        assert_eq!(stats.total_tokens, 150);
        assert_eq!(stats.total_turns, 1);

        stats.record_turn(Some(200), Some(80));
        assert_eq!(stats.prompt_tokens, 300);
        assert_eq!(stats.completion_tokens, 130);
        assert_eq!(stats.total_tokens, 430);
        assert_eq!(stats.total_turns, 2);

        let summary = stats.format_summary();
        assert!(summary.contains("430 total"));
        assert!(summary.contains("300 prompt"));
        assert!(summary.contains("130 completion"));
        assert!(summary.contains("2 turns"));

        stats.reset();
        assert_eq!(stats.total_tokens, 0);
        assert_eq!(stats.total_turns, 0);
    }

    #[test]
    fn test_session_creation_and_messages() {
        let mut session = Session::new("test-model");
        assert_eq!(session.active_model(), "test-model");
        assert_eq!(session.total_messages(), 0);
        assert!(session.title().is_none());

        // 1. Add user message -> auto-title
        session.add_user_message("Hello Fusion, can you help me refactor?");
        assert_eq!(session.total_messages(), 1);
        assert_eq!(
            session.title(),
            Some("Hello Fusion, can you help me refactor?")
        );
        assert_eq!(session.messages()[0].role, Role::User);

        // 2. Add assistant message
        session.add_assistant_message("Yes, I can!");
        assert_eq!(session.total_messages(), 2);
        assert_eq!(session.messages()[1].role, Role::Assistant);

        // 3. Add tool result
        session.add_tool_result("call_123", "Result output");
        assert_eq!(session.total_messages(), 3);
        assert_eq!(session.messages()[2].role, Role::Tool);

        // 4. Record token usage
        session.record_tokens(Some(120), Some(45));
        assert_eq!(session.token_stats().total_tokens, 165);

        // 5. Truncate
        session.truncate(2);
        assert_eq!(session.total_messages(), 2);

        // 6. Clear
        session.clear_messages();
        assert_eq!(session.total_messages(), 0);
    }

    #[test]
    fn test_session_serialization_and_resumption() {
        let temp_dir = std::env::temp_dir().join(format!("fusion_test_{}", Uuid::new_v4()));
        fs::create_dir_all(&temp_dir).unwrap();

        let id = Uuid::new_v4();
        let mut session = Session::with_id(id, "deepseek-chat");
        session.set_title("Rust Architecture Discussion");
        session.set_metadata("provider", "deepseek");
        session.add_user_message("How do we structure subagents in Rust?");
        session
            .add_assistant_message("By using decoupled asynchronous runners and message passing.");
        session.record_usage(250, 100);

        let file_path = temp_dir.join(format!("{}.json", id));
        session.save_to_path(&file_path).unwrap();
        assert!(file_path.exists());

        // Load back
        let loaded = Session::load_from_path(&file_path).unwrap();
        assert_eq!(loaded.id(), id);
        assert_eq!(loaded.active_model(), "deepseek-chat");
        assert_eq!(loaded.title(), Some("Rust Architecture Discussion"));
        assert_eq!(loaded.total_messages(), 2);
        assert_eq!(loaded.token_stats().prompt_tokens, 250);
        assert_eq!(loaded.token_stats().completion_tokens, 100);
        assert_eq!(loaded.token_stats().total_tokens, 350);
        assert_eq!(loaded.get_metadata("provider"), Some("deepseek"));

        // Markdown export test
        let md = loaded.export_markdown();
        assert!(md.contains("# Rust Architecture Discussion"));
        assert!(md.contains("### 👤 User"));
        assert!(md.contains("### 🤖 Assistant"));
        assert!(md.contains("deepseek-chat"));

        // HTML export test
        let html = loaded.export_html();
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("Rust Architecture Discussion"));
        assert!(html.contains("deepseek-chat"));
        assert!(html.contains("data-theme=\"dark\""));
        // Cleanup
        let _ = fs::remove_dir_all(temp_dir);
    }

    #[test]
    fn test_session_summary_and_empty_list() {
        let session = Session::new("claude-3-5-sonnet");
        let summary = SessionSummary {
            id: session.id,
            created_at: session.created_at.clone(),
            updated_at: session.updated_at.clone(),
            active_model: session.active_model.clone(),
            title: Some("Summary Test".to_string()),
            message_count: 0,
            preview: "Empty session".to_string(),
        };

        assert_eq!(summary.active_model, "claude-3-5-sonnet");
        assert_eq!(summary.message_count, 0);
    }
}
